version: 2
updates:
  - package-ecosystem: pip
    directory: /
    open-pull-requests-limit: 25
    schedule:
      interval: weekly
                          
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 25
    schedule:
      interval: weekly
